Revert supported PHP version back to >=7.2.0
arquivei/laravel-prometheus-exporter pull request #6
Opened 2020-03-04 09:53 UTC by ikari7789

Many of the Laravel versions supported by this package still work with PHP 7.2.0 and endclothing/prometheus_client_php also works with PHP 7.2.0. Bumping minimum required language version also seems like a major change and would constitute a major version change rather than a minor version change.

2020-07-31 12:58 UTC, andrelugomes commented
Hi @ikari7789 sorry for the late, we are structuring an open source process internally.

Could you rebase you branch than I'll merge your PR?

2020-09-08 14:03 UTC, andrelugomes requested changes
Could you rebase your commit?

2020-09-09 02:34 UTC, ikari7789 commented
Sorry about the delay. I also fixed testing for each version of Laravel listed as supported. One test fails though, but I don't think it's due to the PHP version?

https://travis-ci.com/github/ikari7789/laravel-prometheus-exporter/jobs/382585377

2020-09-09 12:03 UTC, andrelugomes commented
> Sorry about the delay. I also fixed testing for each version of Laravel listed as supported. One test fails though, but I don't think it's due to the PHP version?
> 
> https://travis-ci.com/github/ikari7789/laravel-prometheus-exporter/jobs/382585377

I don't think so.

Let me look closer, then I'll  reply to you. Ok?

2021-02-12 12:55 UTC, fcoedno commented
Hi @ikari7789. I'm adding support for PHP 7.2 and 8.0 for a next 2.0 release at #15. It also includes the removal of `endclothing/prometheus_client_php` in favor of `promphp/prometheus_client_php`.

2022-05-18 19:05 UTC, closed without merging